import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.FormLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BookForm extends HorizontalLayout {
    protected FormLayout layout;
    protected TextField id;
    protected TextField name;
    protected TextField author;
    protected TextField checkedOut;
    protected TextField userId;
    protected Button delete;
    protected Button save;
    protected Button cancel;
    protected Button checkOut;
    protected Label nSave;
    protected Button add;
    protected Button returnBook;

    public BookForm() {
        Design.read(this);
    }
}
