import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.Button;
import com.vaadin.ui.AbsoluteLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Signin extends AbsoluteLayout {
    protected Button signinButton;
    protected PasswordField passwordField;
    protected TextField username;
    protected Label welcomeLabel;
    protected Label usernameLabel;
    protected Label passwordLabel;
    protected Label signInError;

    public Signin() {
        Design.read(this);
    }
}
